[2023-12-14T00:20:36.608+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.create_domains_table scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2023-12-14T00:20:36.616+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.create_domains_table scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2023-12-14T00:20:36.616+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-12-14T00:20:36.627+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_domains_table> on 2023-12-13 00:00:00+00:00
[2023-12-14T00:20:36.632+0000] {standard_task_runner.py:57} INFO - Started process 239 to run task
[2023-12-14T00:20:36.647+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'create_domains_table', 'scheduled__2023-12-13T00:00:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpgotrxyoj']
[2023-12-14T00:20:36.655+0000] {standard_task_runner.py:85} INFO - Job 104: Subtask create_domains_table
[2023-12-14T00:20:36.727+0000] {task_command.py:416} INFO - Running <TaskInstance: my_dag.create_domains_table scheduled__2023-12-13T00:00:00+00:00 [running]> on host dde03b621bd8
[2023-12-14T00:20:36.781+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='create_domains_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-13T00:00:00+00:00'
[2023-12-14T00:20:36.783+0000] {sql.py:274} INFO - Executing: 
        CREATE TABLE IF NOT EXISTS DomainsToScrape (
            id  SERIAL PRIMARY KEY,
            domain VARCHAR(128) UNIQUE,
            scrapped BOOlEAN
        );
        
[2023-12-14T00:20:36.791+0000] {base.py:73} INFO - Using connection ID 'postgres_hw2' for task execution.
[2023-12-14T00:20:36.796+0000] {base.py:73} INFO - Using connection ID 'postgres_hw2' for task execution.
[2023-12-14T00:20:36.802+0000] {sql.py:418} INFO - Running statement: 
        CREATE TABLE IF NOT EXISTS DomainsToScrape (
            id  SERIAL PRIMARY KEY,
            domain VARCHAR(128) UNIQUE,
            scrapped BOOlEAN
        );
        , parameters: None
[2023-12-14T00:20:36.828+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(domainstoscrape_id_seq, 2200) already exists.

[2023-12-14T00:20:36.843+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=my_dag, task_id=create_domains_table, execution_date=20231213T000000, start_date=20231214T002036, end_date=20231214T002036
[2023-12-14T00:20:36.850+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 104 for task create_domains_table (duplicate key value violates unique constraint "pg_type_typname_nsp_index"
DETAIL:  Key (typname, typnamespace)=(domainstoscrape_id_seq, 2200) already exists.
; 239)
[2023-12-14T00:20:36.887+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-14T00:20:36.904+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
